spring:

  h2:
    console.enabled: true
    console.path: "/h2-console"

  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


---
spring:
  profiles: cloud

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
